# Comment on when an issue is closed
name: Comment issues when closed
on: # This action will trigger when an issue is closed
  issues:
    types:
      - closed
jobs:
  label_issues: # the first job is named as label_issues
    runs-on: ubuntu-latest # This job will run on the latest version of Ubuntu.
    permissions: # This job requires write access to issues in order to add labels and comment.
      issues: write
    steps: # The "steps" section contains the individual tasks that will be performed in this job.
      - name: Comment on issue # The name of the step
        uses: peter-evans/create-or-update-comment@v1 # This step uses the "peter-evans/create-or-update-comment@v1" action to execute a script that adds labels to the issue.
        with:
          issue-number: ${{ github.event.issue.number }} # The issue number is obtained from the context of the event that triggered the action.
          body: | # The body of the comment is a message thanking the user for opening the issue.
           Thanks for CLOSING this issue!
